name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    name: Check Formatting
    runs-on: ubuntu-latest
    container:
      image: silkeh/clang:18
    steps:
      - uses: actions/checkout@v4

      - name: Check Formatting of the each project
        run: make check-fmt

  build:
    name: Build Projects
    needs: check-format
    runs-on: ubuntu-latest
    container:
      image: gcc:14
    steps:
      - uses: actions/checkout@v4

      - name: Build projects
        run: make build
